/**
 * Minimal country-name -> ISO 3166-1 alpha-2 map for the one-off places
 * backfill (scripts/backfill-places.ts). Keys are normalised (lowercase,
 * alphanumerics + single spaces). Covers common English names, a few common
 * alternates, and every country present in the current tree. Unrecognised
 * names fall through to an unfiltered match, so this does not need to be
 * exhaustive.
 */
export const COUNTRY_NAME_TO_ISO: Record<string, string> = {
  afghanistan: "AF",
  albania: "AL",
  algeria: "DZ",
  argentina: "AR",
  australia: "AU",
  austria: "AT",
  bangladesh: "BD",
  belgium: "BE",
  bermuda: "BM",
  brazil: "BR",
  bulgaria: "BG",
  canada: "CA",
  chile: "CL",
  china: "CN",
  colombia: "CO",
  croatia: "HR",
  cuba: "CU",
  cyprus: "CY",
  "czech republic": "CZ",
  czechia: "CZ",
  denmark: "DK",
  "democratic republic of the congo": "CD",
  "dr congo": "CD",
  egypt: "EG",
  ethiopia: "ET",
  finland: "FI",
  france: "FR",
  germany: "DE",
  ghana: "GH",
  greece: "GR",
  "hong kong": "HK",
  hungary: "HU",
  iceland: "IS",
  india: "IN",
  indonesia: "ID",
  iran: "IR",
  iraq: "IQ",
  ireland: "IE",
  israel: "IL",
  italy: "IT",
  jamaica: "JM",
  japan: "JP",
  jordan: "JO",
  kenya: "KE",
  kuwait: "KW",
  lebanon: "LB",
  madagascar: "MG",
  malawi: "MW",
  malaysia: "MY",
  mauritius: "MU",
  mexico: "MX",
  morocco: "MA",
  mozambique: "MZ",
  myanmar: "MM",
  burma: "MM",
  nepal: "NP",
  netherlands: "NL",
  "the netherlands": "NL",
  "new zealand": "NZ",
  nigeria: "NG",
  norway: "NO",
  pakistan: "PK",
  "the philippines": "PH",
  philippines: "PH",
  poland: "PL",
  portugal: "PT",
  qatar: "QA",
  romania: "RO",
  russia: "RU",
  "russian federation": "RU",
  rwanda: "RW",
  "saudi arabia": "SA",
  singapore: "SG",
  "south africa": "ZA",
  "south korea": "KR",
  "korea": "KR",
  spain: "ES",
  "sri lanka": "LK",
  ceylon: "LK",
  sudan: "SD",
  sweden: "SE",
  switzerland: "CH",
  syria: "SY",
  taiwan: "TW",
  tanzania: "TZ",
  "united republic of tanzania": "TZ",
  tanganyika: "TZ",
  zanzibar: "TZ",
  thailand: "TH",
  tunisia: "TN",
  turkey: "TR",
  "turkiye": "TR",
  uganda: "UG",
  ukraine: "UA",
  "united arab emirates": "AE",
  uae: "AE",
  "united kingdom": "GB",
  uk: "GB",
  "great britain": "GB",
  england: "GB",
  scotland: "GB",
  wales: "GB",
  "northern ireland": "GB",
  "united states": "US",
  "united states of america": "US",
  usa: "US",
  us: "US",
  america: "US",
  vietnam: "VN",
  yemen: "YE",
  zambia: "ZM",
  zimbabwe: "ZW",
  rhodesia: "ZW",
};
